version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/frontend

permissions:
  - object: /home/ubuntu/frontend
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: shell-scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: shell-scripts/start_server.sh
      timeout: 300
      runas: ubuntu